name: C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v1

    - name: install deps
      run: sudo apt update && sudo apt install -y wget git bash gcc gfortran g++ make file libopenmpi3 slurm libopenmpi-dev libfuse2 fuse2fs sshpass

    - name: Configure CMake
      run: cmake -S . -B build  

    - name: Build
      run: cmake --build build

    - name: Run Tests
      run: ctest --test-dir build

    - name: experimenting
      run: wget https://github.com/sylabs/singularity/releases/download/v4.1.3/singularity-ce_4.1.3-focal_amd64.deb && sudo dpkg -i singularity-ce_4.1.3-focal_amd64.deb

    - name: create singularity image
      run: sudo singularity build --notest matrixMul.sif matrixMul.def

    - name: Transfer singularity image with sshpass
      run: sshpass -p "${{secrets.CENECA_SECRET}}" scp -o StrictHostKeyChecking=no {matrixMul.sif,job.sh,matrixA.txt,matrixB.txt,build/main}  a08trb71@login.g100.cineca.it:~

    - name: delete cineca from known hosts
      run: ssh-keygen -f "/home/runner/.ssh/known_hosts" -R "login.g100.cineca.it"

    - name: add chmod
      run: sshpass -p "${{secrets.CENECA_SECRET}}" ssh -o StrictHostKeyChecking=no a08trb71@login.g100.cineca.it << 'EOF'
            # Commands to run on the remote server
            echo "Running on remote server"
            chmod +x job.sh
            # Add your commands here
          EOF

    - name: remove previous logs and run job via SSH and get results
      run: sshpass -p "${{secrets.CENECA_SECRET}}" ssh -o StrictHostKeyChecking=no a08trb71@login.g100.cineca.it && " sbatch job.sh && sleep 60 && cat stdout.out "
